const vsCodeSettings = require('./.vscode/settings.json');

module.exports = {
  $schema:
    'https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json',
  allowCompoundWords: true,
  caseSensitive: true,
  import: ['@cspell/dict-pt-br/cspell-ext.json'],
  dictionaries: [
    'bash',
    'en_us',
    'en-gb',
    'pt-br',
    'fullstack',
    'html',
    'lorem-ipsum',
    'node',
    'npm',
    'fullstack',
    'softwareTerms',
    'typescript',
  ],
  ignorePaths: [
    'dist',
    'node_modules',
    'local',
    'package.json',
    'pnpm-lock.yaml',
    'tmp',
    '.vscode',
    '.gitignore',
    'cspell.config.js',
    '*.snap',
    '*.svg',
    'coverage',
    '*.log',
    '*.min.js',
    '.git',
    'cspell.config.cjs',
    'brazil-municipalities.json',
  ],
  language: 'en',
  useGitignore: true,
  words: vsCodeSettings['cSpell.words'],
  ignoreRegExpList: [
    '/ipfs:\\/\\/[^\\s"\']+/',
    '/\\b(?:bafy[a-z0-9]{20,}|Qm[1-9A-HJ-NP-Za-km-z]{20,})\\b/',
    '/\\bk[a-z0-9]{40,}\\b/',
    '/\\blibp[a-z0-9-]*\\b/i',
    '/\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b/i',
  ],
};
